{{- if .Values.controlplane.create }}
apiVersion: datasance.com/v3
kind: ControlPlane
metadata:
  name: {{ default .Release.Name .Values.controlplane.name }}
  namespace: {{ default .Release.Namespace .Values.controlplane.namespace }}
  labels:
    {{- include "pot.labels" . | nindent 4 }}
    {{- with .Values.controlplane.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controlplane.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{/* Validate required auth fields so installs fail fast when omitted */}}
  {{- $auth := .Values.controlplane.spec.auth }}
  {{- $authURL := required "controlplane.spec.auth.url is required" $auth.url }}
  {{- $authRealm := required "controlplane.spec.auth.realm is required" $auth.realm }}
  {{- $authRealmKey := required "controlplane.spec.auth.realmKey is required" $auth.realmKey }}
  {{- $authSSL := required "controlplane.spec.auth.ssl is required" $auth.ssl }}
  {{- $authControllerClient := required "controlplane.spec.auth.controllerClient is required" $auth.controllerClient }}
  {{- $authControllerSecret := required "controlplane.spec.auth.controllerSecret is required" $auth.controllerSecret }}
  {{- $authViewerClient := required "controlplane.spec.auth.viewerClient is required" $auth.viewerClient }}
  {{- with .Values.controlplane.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

