# Global overrides
nameOverride: "iofog-operator"
fullnameOverride: "iofog-operator"

imagePullSecrets: []

crds:
  install: true

rbac:
  create: true

operator:
  replicaCount: 1
  image: ghcr.io/datasance/operator:3.6.0
  imagePullPolicy: Always
  serviceAccount:
    create: true
    name: "iofog-operator"
    annotations: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  imagePullSecrets: []
  extraEnv: []
  extraArgs: []

controlplane:
  create: true
  name: pot
  namespace: ""
  annotations: {}
  labels: {}
  spec:
    replicas:
      controller: 1
    # database:
    #   provider: postgres
    #   user: ""
    #   host: ""
    #   port: 5432
    #   password: ""
    #   databaseName: ""
    #   ssl: false
    #   ca: ""
    auth:
      # REQUIRED: set all auth fields (Keycloak / OpenID Connect Client identity)
      url: ""
      realm: ""
      realmKey: ""
      ssl: ""
      controllerClient: ""
      controllerSecret: ""
      viewerClient: ""
    events:
      auditEnabled: true
      retentionDays: 14
      cleanupInterval: 86400
      captureIpAddress: true
    images:
      # pullSecret: ""
      controller: "ghcr.io/datasance/controller:3.6.0"
      router: "ghcr.io/datasance/router:3.6.0"
    services:
      controller:
        type: LoadBalancer
        # address: ""
        # annotations: {}
      router:
        type: LoadBalancer
        # address: ""
        # annotations: {}
    controller:
      # pidBaseDir: ""
      # ecnViewerPort: 0
      # ecnViewerUrl: ""
      https: false
      # secretName: ""
      logLevel: "info"
    # ingresses:
    #   controller:
    #     annotations: {}
    #     ingressClassName: ""
    #     host: ""
    #     secretName: ""
    #   router:
    #     address: ""
    #     messagePort: 5671
    #     interiorPort: 55671
    #     edgePort: 45671

