{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pot.fullname" . }}
  labels:
    {{- include "pot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pot.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pot.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

